package CapaInterfaz.pnlsSecundarios.pnlsEstudiante;

import CapaDatos.ClsRecursividad;

public class FrmRecursos extends javax.swing.JFrame {
    
    /**
     * Creates new form MainFrame
     */

    public FrmRecursos() {
        initComponents();
        this.setLocationRelativeTo(null); //Centra la ventana
        this.setSize(850, 529);
        this.setResizable(false);
        //this.setExtendedState(MAXIMIZED_BOTH); //Maximiza la ventana
        txaImp.setEditable(false);
        ocultarPaneles();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmbEjercicios = new javax.swing.JComboBox<>();
        pnl1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt01_PNL01 = new javax.swing.JTextField();
        btnEj1 = new javax.swing.JButton();
        pnlImpresion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaImp = new javax.swing.JTextArea();
        pnl2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt01_PNL02 = new javax.swing.JTextField();
        btnEj2 = new javax.swing.JButton();
        txt02_PNL02 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt01_PNL03 = new javax.swing.JTextField();
        btnEj3 = new javax.swing.JButton();
        pnl4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt01_PNL04 = new javax.swing.JTextField();
        btnEj4 = new javax.swing.JButton();
        pnl5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt01_PNL05 = new javax.swing.JTextField();
        btnEj5 = new javax.swing.JButton();
        txt02_PNL05 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pnl6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt01_PNL6 = new javax.swing.JTextField();
        btnEj6 = new javax.swing.JButton();
        txt02_PNL6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pnl7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt01_PNL7 = new javax.swing.JTextField();
        btnEj7 = new javax.swing.JButton();
        pnl8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt01_PNL8 = new javax.swing.JTextField();
        btnEj8 = new javax.swing.JButton();
        pnl9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt01_PNL9 = new javax.swing.JTextField();
        btnEj9 = new javax.swing.JButton();
        pnl10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt01_PNL10 = new javax.swing.JTextField();
        btnEj10 = new javax.swing.JButton();
        pnl_11 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt01_PNL_11 = new javax.swing.JTextField();
        btnEj_11 = new javax.swing.JButton();
        pnl_12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt01_PNL_12 = new javax.swing.JTextField();
        btnEj_12 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Escoja el Ejercicio"));

        cmbEjercicios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ejercicio 1 - Mostrar los números de 1 a n", "Ejercicio 2 -  Generar la tabla de multiplicar de un número", "Ejercicio 3 -  Sumar los divisores de un número", "Ejercicio 4 -  Determinar si un número es perfecto", "Ejercicio 5 - Calcular el producto de dos números", "Ejercicio 6 - Calcular el Mínimo Común Múltiplo (MCM) de dos números", "Ejercicio 7 - Convertir un número decimal a binario", "Ejercicio 8 -  Convertir un número binario a decimal", "Ejercicio 9 -  Determinar si una cadena es palíndromo", "Ejercicio 10 -  Mostrar los primeros n términos de la serie Fibonacci", "Ejercicio 11 -  Invertir el orden de los dígitos que conforman un número", "Ejercicio 12 - Determinar si un número es primo" }));
        cmbEjercicios.setSelectedIndex(-1);
        cmbEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEjerciciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbEjercicios, 0, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbEjercicios)
                .addContainerGap())
        );

        pnl1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 01"));

        jLabel1.setText("Mostrar los números de 1 a n");

        jLabel2.setText("Ingrese N:");

        btnEj1.setText("Ingresar");
        btnEj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEj1)
                            .addComponent(txt01_PNL01, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52)))
                .addGap(29, 29, 29))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt01_PNL01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEj1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlImpresion.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        txaImp.setColumns(20);
        txaImp.setRows(5);
        jScrollPane1.setViewportView(txaImp);

        javax.swing.GroupLayout pnlImpresionLayout = new javax.swing.GroupLayout(pnlImpresion);
        pnlImpresion.setLayout(pnlImpresionLayout);
        pnlImpresionLayout.setHorizontalGroup(
            pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpresionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlImpresionLayout.setVerticalGroup(
            pnlImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImpresionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pnl2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 02"));

        jLabel3.setText("Generar la tabla de multiplicar de un número");

        jLabel4.setText("Tabla del:");

        btnEj2.setText("Ingresar");
        btnEj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Hasta el:");

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnl2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txt01_PNL02, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txt02_PNL02, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl2Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel3)))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnEj2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt02_PNL02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txt01_PNL02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnEj2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 03"));

        jLabel6.setText("Sumar los divisores de N");

        jLabel7.setText("Ingrese N:");

        btnEj3.setText("Ingresar");
        btnEj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEj3)
                            .addComponent(txt01_PNL03, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52)))
                .addGap(29, 29, 29))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt01_PNL03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEj3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 04"));

        jLabel8.setText("Un número n es perfecto?");

        jLabel9.setText("Ingrese N:");

        btnEj4.setText("Ingresar");
        btnEj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEj4)
                            .addComponent(txt01_PNL04, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52)))
                .addGap(29, 29, 29))
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt01_PNL04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEj4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 05"));

        jLabel10.setText("Multiplicar dos números");

        jLabel11.setText("N1: ");

        btnEj5.setText("Ingresar");
        btnEj5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj5ActionPerformed(evt);
            }
        });

        jLabel12.setText("N2:");

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(97, 97, 97))
            .addGroup(pnl5Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnEj5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt01_PNL05, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txt02_PNL05, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txt01_PNL05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txt02_PNL05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnEj5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl6.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 06"));

        jLabel13.setText("Minimo Comun Múltiplo de 2 Números");

        jLabel14.setText("N1: ");

        btnEj6.setText("Ingresar");
        btnEj6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj6ActionPerformed(evt);
            }
        });

        jLabel15.setText("N2:");

        javax.swing.GroupLayout pnl6Layout = new javax.swing.GroupLayout(pnl6);
        pnl6.setLayout(pnl6Layout);
        pnl6Layout.setHorizontalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt01_PNL6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(txt02_PNL6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(pnl6Layout.createSequentialGroup()
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl6Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnEj6))
                    .addGroup(pnl6Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl6Layout.setVerticalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txt01_PNL6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txt02_PNL6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnEj6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl7.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 07"));

        jLabel19.setText("Convertir un número de decimal a binario");

        jLabel20.setText("Ingrese N:");

        btnEj7.setText("Ingresar");
        btnEj7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl7Layout = new javax.swing.GroupLayout(pnl7);
        pnl7.setLayout(pnl7Layout);
        pnl7Layout.setHorizontalGroup(
            pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl7Layout.createSequentialGroup()
                .addGroup(pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addGroup(pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEj7)
                            .addComponent(txt01_PNL7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl7Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel19)))
                .addContainerGap())
        );
        pnl7Layout.setVerticalGroup(
            pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt01_PNL7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEj7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl8.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 08"));

        jLabel21.setText("Convertir un número de binario a decimal");

        jLabel22.setText("Ingrese N:");

        btnEj8.setText("Ingresar");
        btnEj8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl8Layout = new javax.swing.GroupLayout(pnl8);
        pnl8.setLayout(pnl8Layout);
        pnl8Layout.setHorizontalGroup(
            pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl8Layout.createSequentialGroup()
                .addGroup(pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl8Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addGroup(pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEj8)
                            .addComponent(txt01_PNL8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl8Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel21)))
                .addContainerGap())
        );
        pnl8Layout.setVerticalGroup(
            pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt01_PNL8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEj8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl9.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 09"));

        jLabel23.setText("Una cadena es palindromo?");

        jLabel24.setText("Ingrese:");

        btnEj9.setText("Ingresar");
        btnEj9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl9Layout = new javax.swing.GroupLayout(pnl9);
        pnl9.setLayout(pnl9Layout);
        pnl9Layout.setHorizontalGroup(
            pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl9Layout.createSequentialGroup()
                .addGroup(pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl9Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt01_PNL9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl9Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnEj9))))
                    .addGroup(pnl9Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel23)))
                .addContainerGap())
        );
        pnl9Layout.setVerticalGroup(
            pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt01_PNL9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEj9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl10.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 10"));

        jLabel25.setText("Serie de Fibonacci hasta N");

        jLabel26.setText("Ingrese N:");

        btnEj10.setText("Ingresar");
        btnEj10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl10Layout = new javax.swing.GroupLayout(pnl10);
        pnl10.setLayout(pnl10Layout);
        pnl10Layout.setHorizontalGroup(
            pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl10Layout.createSequentialGroup()
                .addGroup(pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl10Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addGroup(pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt01_PNL10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl10Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnEj10))))
                    .addGroup(pnl10Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel25)))
                .addContainerGap())
        );
        pnl10Layout.setVerticalGroup(
            pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt01_PNL10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEj10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_11.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 11"));

        jLabel29.setText("Invertir el orden de los números");

        jLabel30.setText("Ingrese N:");

        btnEj_11.setText("Ingresar");
        btnEj_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj_11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_11Layout = new javax.swing.GroupLayout(pnl_11);
        pnl_11.setLayout(pnl_11Layout);
        pnl_11Layout.setHorizontalGroup(
            pnl_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_11Layout.createSequentialGroup()
                .addGroup(pnl_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_11Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt01_PNL_11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_11Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnEj_11))))
                    .addGroup(pnl_11Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel29)))
                .addContainerGap())
        );
        pnl_11Layout.setVerticalGroup(
            pnl_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt01_PNL_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEj_11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_12.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicio 11"));

        jLabel31.setText("Un número N es primo?");

        jLabel32.setText("Ingrese N:");

        btnEj_12.setText("Ingresar");
        btnEj_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEj_12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_12Layout = new javax.swing.GroupLayout(pnl_12);
        pnl_12.setLayout(pnl_12Layout);
        pnl_12Layout.setHorizontalGroup(
            pnl_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(pnl_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(txt01_PNL_12, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_12Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnEj_12)))
                .addContainerGap())
        );
        pnl_12Layout.setVerticalGroup(
            pnl_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt01_PNL_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEj_12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl2, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlImpresion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlImpresion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEjerciciosActionPerformed
        // TODO add your handling code here:
        switch (cmbEjercicios.getSelectedIndex()+1) {
            case 1: ocultarPaneles(); pnl1.setVisible(true); break;
            case 2: ocultarPaneles(); pnl2.setVisible(true); break;
            case 3: ocultarPaneles(); pnl3.setVisible(true); break;
            case 4: ocultarPaneles(); pnl4.setVisible(true); break;
            case 5: ocultarPaneles(); pnl5.setVisible(true); break;
            case 6: ocultarPaneles(); pnl6.setVisible(true); break;
            case 7: ocultarPaneles(); pnl7.setVisible(true); break;
            case 8: ocultarPaneles(); pnl8.setVisible(true); break;
            case 9: ocultarPaneles(); pnl9.setVisible(true); break;
            case 10: ocultarPaneles(); pnl10.setVisible(true); break;
            case 11: ocultarPaneles(); pnl_11.setVisible(true); break;
            case 12: ocultarPaneles(); pnl_12.setVisible(true); break;
        }
        
    }//GEN-LAST:event_cmbEjerciciosActionPerformed

    private void btnEj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj1ActionPerformed
        try{
            txaImp.setText(ClsRecursividad.Ej01_numero1aN(1, Integer.parseInt(txt01_PNL01.getText()), ""));
        }catch(Exception e){ }
    }//GEN-LAST:event_btnEj1ActionPerformed

    private void btnEj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj2ActionPerformed
        try{
            String str= ClsRecursividad.Ej02_tablaMultiplicar(
                    Integer.parseInt(txt01_PNL02.getText()), Integer.parseInt(txt02_PNL02.getText()),"");
            txaImp.setText(str);
        }catch(Exception e){ }
    }//GEN-LAST:event_btnEj2ActionPerformed

    private void btnEj3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj3ActionPerformed
        try{  
            int n = Integer.parseInt(txt01_PNL03.getText());
            txaImp.setText(Integer.toString(ClsRecursividad.Ej03_sumaDivisores(n, n)));
        }catch(Exception e){ System.err.println("ERROR"); }
    }//GEN-LAST:event_btnEj3ActionPerformed

    private void btnEj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj4ActionPerformed
       try{  
            int n = Integer.parseInt(txt01_PNL04.getText());
            if(n == ClsRecursividad.Ej04_numPerfecto(n/2, n)){
                txaImp.setText("Si es Perfecto");
            } else {
                txaImp.setText("No es Perfecto");
            }
        }catch(Exception e){ System.err.println("ERROR"); }
    }//GEN-LAST:event_btnEj4ActionPerformed

    private void btnEj5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj5ActionPerformed
        try{
            String str= ClsRecursividad.Ej05_multiplicar(
                    Integer.parseInt(txt01_PNL05.getText()), Integer.parseInt(txt02_PNL05.getText()));
            txaImp.setText(str);
        }catch(Exception e){ System.err.println("ERROR"); }
    }//GEN-LAST:event_btnEj5ActionPerformed

    private void btnEj6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj6ActionPerformed
        try{
            String str= Integer.toString(ClsRecursividad.Ej06_MinimoComunMultiplo(
                    Integer.parseInt(txt01_PNL6.getText()), Integer.parseInt(txt02_PNL6.getText())));
            txaImp.setText(str);
        }catch(Exception e){ System.err.println("ERROR"); }
    }//GEN-LAST:event_btnEj6ActionPerformed

    private void btnEj7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj7ActionPerformed
        try{
            String str= Integer.toString(ClsRecursividad.Ej07_decimalBinario(
                    Integer.parseInt(txt01_PNL7.getText())));
            txaImp.setText(str);
        }catch(Exception e){ System.err.println("ERROR"); }
    }//GEN-LAST:event_btnEj7ActionPerformed

    private void btnEj8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj8ActionPerformed
        try{
            txaImp.setText(Integer.toString(ClsRecursividad.Ej08_binarioDecimal(txt01_PNL8.getText(), 0)));
        }catch(Exception e){ System.err.println("ERROR"); }
    }//GEN-LAST:event_btnEj8ActionPerformed

    private void btnEj9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj9ActionPerformed
        try{  
            int n = txt01_PNL9.getText().length();
            if(ClsRecursividad.Ej09_palindromo(txt01_PNL9.getText(), 0, n-1)){
                txaImp.setText("Si es Palindromo");
            } else {
                txaImp.setText("No es Palindromo");
            }
        }catch(Exception e){ System.err.println("ERROR"); }
    }//GEN-LAST:event_btnEj9ActionPerformed

    private void btnEj10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj10ActionPerformed
        try{  
            String str = "";
            for(int i=0; i< Integer.parseInt(txt01_PNL10.getText()); i++){
                str += " " + ClsRecursividad.Ej10_fibonacci(i);
            }
            txaImp.setText(str);
        }catch(Exception e){ System.err.println("ERROR"); }
    }//GEN-LAST:event_btnEj10ActionPerformed

    private void btnEj_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj_11ActionPerformed
        try{
            txaImp.setText(ClsRecursividad.Ej11_invertirOrden("", Integer.parseInt(txt01_PNL_11.getText())));
        } catch (Exception e){ System.err.println("ERROR"); }   
    }//GEN-LAST:event_btnEj_11ActionPerformed

    private void btnEj_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEj_12ActionPerformed
        try{  
            if(ClsRecursividad.Ej12_esPrimo(Integer.parseInt(txt01_PNL_12.getText()), 2)){
                txaImp.setText("Si es Primo");
            } else {
                txaImp.setText("No es Primo");
            }
        }catch(Exception e){ System.err.println("ERROR"); }
    }//GEN-LAST:event_btnEj_12ActionPerformed
    
    private void ocultarPaneles(){
        pnl1.setVisible(false); 
        pnl2.setVisible(false); 
        pnl3.setVisible(false);
        pnl4.setVisible(false);
        pnl5.setVisible(false);
        pnl6.setVisible(false);
        pnl7.setVisible(false);
        pnl8.setVisible(false);
        pnl9.setVisible(false);
        pnl10.setVisible(false);
        pnl_11.setVisible(false);
        pnl_12.setVisible(false);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRecursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRecursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEj1;
    private javax.swing.JButton btnEj10;
    private javax.swing.JButton btnEj2;
    private javax.swing.JButton btnEj3;
    private javax.swing.JButton btnEj4;
    private javax.swing.JButton btnEj5;
    private javax.swing.JButton btnEj6;
    private javax.swing.JButton btnEj7;
    private javax.swing.JButton btnEj8;
    private javax.swing.JButton btnEj9;
    private javax.swing.JButton btnEj_11;
    private javax.swing.JButton btnEj_12;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbEjercicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl10;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl7;
    private javax.swing.JPanel pnl8;
    private javax.swing.JPanel pnl9;
    private javax.swing.JPanel pnlImpresion;
    private javax.swing.JPanel pnl_11;
    private javax.swing.JPanel pnl_12;
    private javax.swing.JTextArea txaImp;
    private javax.swing.JTextField txt01_PNL01;
    private javax.swing.JTextField txt01_PNL02;
    private javax.swing.JTextField txt01_PNL03;
    private javax.swing.JTextField txt01_PNL04;
    private javax.swing.JTextField txt01_PNL05;
    private javax.swing.JTextField txt01_PNL10;
    private javax.swing.JTextField txt01_PNL6;
    private javax.swing.JTextField txt01_PNL7;
    private javax.swing.JTextField txt01_PNL8;
    private javax.swing.JTextField txt01_PNL9;
    private javax.swing.JTextField txt01_PNL_11;
    private javax.swing.JTextField txt01_PNL_12;
    private javax.swing.JTextField txt02_PNL02;
    private javax.swing.JTextField txt02_PNL05;
    private javax.swing.JTextField txt02_PNL6;
    // End of variables declaration//GEN-END:variables
}
