/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz.pnlsSecundarios.pnlsAdministrador;

import CapaInterfaz.FrmMenuPrincipal;
import CapaNegocio.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class PnlListar extends javax.swing.JPanel {

    DefaultTableModel tablaDocentes;
    DefaultTableModel tablaEstudiantes;
    public PnlListar() {
        initComponents();
        tablaDocentes = new DefaultTableModel();
        tablaDocentes.addColumn("Nombre");
        tablaDocentes.addColumn("Apellido");
        tblDocentes.setModel(tablaDocentes);
        tablaEstudiantes = new DefaultTableModel();
        tablaEstudiantes.addColumn("Nombre");
        tablaEstudiantes.addColumn("Apellido");
        tblEstudiantes.setModel(tablaEstudiantes);
    }
    
    public void llenarTablas(){
        // limpiar la tabla
        try {
            tablaDocentes.setRowCount(0);
            tablaEstudiantes.setRowCount(0);
            for (ClsDocente d : FrmMenuPrincipal.docentes) {
                tablaDocentes.addRow(new Object[]{d.getNombre(), d.getApellido()});
            }
            for (ClsEstudiante e : FrmMenuPrincipal.estudiantes) {
                tablaEstudiantes.addRow(new Object[]{e.getNombre(), e.getApellido()});
            }
            /*for (ClsEstudiante e : FrmMenuPrincipal.estudiantes) {
                double[] calificaciones = e.getCalificaciones();
                tablaEstudiantes.addRow(new Object[]{calificaciones[0], calificaciones[1],
                    calificaciones[2], calificaciones[3], calificaciones[4], calificaciones[5],
                    calificaciones[6], calificaciones[7], calificaciones[8], calificaciones[9]});
            }*/
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocentes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();

        tblDocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDocentes);

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEstudiantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDocentes;
    private javax.swing.JTable tblEstudiantes;
    // End of variables declaration//GEN-END:variables
}
