/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz.panelesSecundarios;

import CapaInterfaz.FrmMenuPrincipal;
import CapaInterfaz.panelesPrincipales.PnlAdministrador;
import CapaNegocio.ClsNivel;
import java.util.ArrayList;
import javax.swing.JOptionPane; // 270.17
import javax.swing.JPanel;

public class PnlNivel extends javax.swing.JPanel {

    
    /**
     * Creates new form PnlNivel
     */
    public PnlNivel() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkExpresionOral = new javax.swing.JCheckBox();
        chkUsoDeTI = new javax.swing.JCheckBox();
        chkIngles = new javax.swing.JCheckBox();
        chkCapacidadAnalisis = new javax.swing.JCheckBox();
        chkRazonamiento = new javax.swing.JCheckBox();
        chkCompresion = new javax.swing.JCheckBox();
        txtNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 300));

        jLabel1.setText("Nombre");

        jLabel2.setText("Requisitos");

        chkExpresionOral.setText("Expresión Oral");

        chkUsoDeTI.setText("Uso de TI");

        chkIngles.setText("Nivel básico de Inglés");

        chkCapacidadAnalisis.setText("Capacidad Análisis");

        chkRazonamiento.setText("Razonamiento Numérico");

        chkCompresion.setText("Compresión Lectora");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkExpresionOral)
                            .addComponent(chkUsoDeTI))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkIngles)
                            .addComponent(chkCapacidadAnalisis))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCompresion)
                            .addComponent(chkRazonamiento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkExpresionOral)
                    .addComponent(chkIngles)
                    .addComponent(chkRazonamiento))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkUsoDeTI)
                    .addComponent(chkCapacidadAnalisis)
                    .addComponent(chkCompresion))
                .addGap(93, 93, 93)
                .addComponent(jButton1)
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList <String> requisistos = new ArrayList();
        if( chkExpresionOral.isSelected()) requisistos.add("Expresion Oral");
        if( chkCapacidadAnalisis.isSelected()) requisistos.add("Expresion Oral");
        if( chkCompresion.isSelected()) requisistos.add("Expresion Oral");
        if( chkIngles.isSelected()) requisistos.add("Expresion Oral");
        if( chkRazonamiento.isSelected()) requisistos.add("Expresion Oral");
        if( chkUsoDeTI.isSelected()) requisistos.add("Expresion Oral");
        
        FrmMenuPrincipal.niveles.add(new ClsNivel(txtNombre.getText(), requisistos));
        JOptionPane.showMessageDialog(null, "El nivel se registro con exito"); 
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkCapacidadAnalisis;
    private javax.swing.JCheckBox chkCompresion;
    private javax.swing.JCheckBox chkExpresionOral;
    private javax.swing.JCheckBox chkIngles;
    private javax.swing.JCheckBox chkRazonamiento;
    private javax.swing.JCheckBox chkUsoDeTI;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
