/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz.pnlsPrincipales;

import CapaInterfaz.pnlsSecundarios.pnlsAdministrador.*;

public class PnlAdministrador extends javax.swing.JPanel {
    
    PnlNivel pnlNivel;
    PnlRegistroCurso pnlCurso;
    PnlCategoria pnlCategoria;
    PnlEliminarDocente pnlEliminarDocente;
    PnlEliminarEstudiante pnlEliminarEstudiante;
    PnlListar pnlListar;

    public PnlAdministrador() {
        initComponents();
        pnlNivel = new PnlNivel();
        pnlCurso = new PnlRegistroCurso();
        pnlCategoria = new PnlCategoria();
        pnlEliminarDocente = new PnlEliminarDocente();
        pnlEliminarEstudiante = new PnlEliminarEstudiante();
        pnlListar = new PnlListar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContenedor = new javax.swing.JPanel();
        btnNivel = new javax.swing.JButton();
        btnCurso = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnDocente = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEstudiante = new javax.swing.JButton();

        btnNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 22.png"))); // NOI18N
        btnNivel.setText("Agregar Nivel");
        btnNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelActionPerformed(evt);
            }
        });

        btnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 2.png"))); // NOI18N
        btnCurso.setText("Agregar Curso");
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 23.png"))); // NOI18N
        btnCategoria.setText("Agregar Categoría");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 9.png"))); // NOI18N
        btnDocente.setText("Eliminar Docente");
        btnDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteActionPerformed(evt);
            }
        });

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 36.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 6.png"))); // NOI18N
        btnEstudiante.setText("Eliminar Estudiante");
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pContenedorLayout = new javax.swing.GroupLayout(pContenedor);
        pContenedor.setLayout(pContenedorLayout);
        pContenedorLayout.setHorizontalGroup(
            pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContenedorLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnNivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(btnCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(btnEstudiante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(99, 99, 99))
        );

        pContenedorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCategoria, btnCurso, btnDocente, btnListar, btnNivel});

        pContenedorLayout.setVerticalGroup(
            pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContenedorLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCurso))
                .addGap(66, 66, 66)
                .addGroup(pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocente)
                    .addComponent(btnEstudiante))
                .addGap(57, 57, 57))
        );

        pContenedorLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCategoria, btnCurso, btnDocente, btnListar, btnNivel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelActionPerformed
        // TODO add your handling code here:
        pContenedor.setVisible(false);
        pnlNivel.setVisible(true);
        pnlNivel.setSize(850, 529);
        pnlNivel.setLocation(0, 0);
        add(pnlNivel);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnNivelActionPerformed

    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
        
        pnlCurso.mostrarCategorias();
        pnlCurso.mostrarDocentes();
        pnlCurso.mostrarNiveles();
              
        pContenedor.setVisible(false);
        pnlCurso.setVisible(true);
        pnlCurso.setSize(850, 529);
        pnlCurso.setLocation(0, 0);
        add(pnlCurso);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnCursoActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        pContenedor.setVisible(false);
        pnlCategoria.setVisible(true);
        pnlCategoria.setSize(850, 529);
        pnlCategoria.setLocation(0, 0);
        add(pnlCategoria);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteActionPerformed
        pContenedor.setVisible(false);
        pnlEliminarDocente.setVisible(true);
        pnlEliminarDocente.setSize(850, 529);
        pnlEliminarDocente.setLocation(0, 0);
        add(pnlEliminarDocente);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnDocenteActionPerformed

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        pContenedor.setVisible(false);
        pnlEliminarEstudiante.setVisible(true);
        pnlEliminarEstudiante.setSize(850, 529);
        pnlEliminarEstudiante.setLocation(0, 0);
        add(pnlEliminarEstudiante);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        pContenedor.setVisible(false);
        pnlListar.llenarTablas();
        pnlListar.setVisible(true);
        pnlListar.setSize(850, 529);
        pnlListar.setLocation(0, 0);
        add(pnlListar);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnListarActionPerformed
    
    public void limpiar(){
        pnlNivel.setVisible(false);
        pnlCurso.setVisible(false);
        pnlCategoria.setVisible(false);
        pnlEliminarDocente.setVisible(false);
        pnlEliminarEstudiante.setVisible(false);
        pnlListar.setVisible(false);
        
        pContenedor.setVisible(true);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnCurso;
    private javax.swing.JButton btnDocente;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnNivel;
    private javax.swing.JPanel pContenedor;
    // End of variables declaration//GEN-END:variables
}
