/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz.pnlsPrincipales;

import CapaInterfaz.pnlsSecundarios.pnlsDocente.PnlNotas;
import CapaInterfaz.pnlsSecundarios.pnlsDocente.PnlRegistroDocente;

/**
 *
 * @author danie
 */
public class PnlDocente extends javax.swing.JPanel {
    
    PnlRegistroDocente pnlRegistrarDocente;
    PnlNotas pnlNotas;
    
    public PnlDocente() {
        initComponents();
        pnlRegistrarDocente = new PnlRegistroDocente();
        pnlNotas = new PnlNotas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContenedor = new javax.swing.JPanel();
        btnRegistroDocente = new javax.swing.JButton();
        btnIngresoCalificaciones = new javax.swing.JButton();

        btnRegistroDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 9.png"))); // NOI18N
        btnRegistroDocente.setText("Registro del Docente");
        btnRegistroDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroDocenteActionPerformed(evt);
            }
        });

        btnIngresoCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 7.png"))); // NOI18N
        btnIngresoCalificaciones.setText("Ingreso de Calificaciones");
        btnIngresoCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoCalificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pContenedorLayout = new javax.swing.GroupLayout(pContenedor);
        pContenedor.setLayout(pContenedorLayout);
        pContenedorLayout.setHorizontalGroup(
            pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContenedorLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnRegistroDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnIngresoCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pContenedorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIngresoCalificaciones, btnRegistroDocente});

        pContenedorLayout.setVerticalGroup(
            pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContenedorLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresoCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pContenedorLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnIngresoCalificaciones, btnRegistroDocente});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroDocenteActionPerformed
        // TODO add your handling code here:
        pContenedor.setVisible(false);
        pnlRegistrarDocente.setVisible(true);
        pnlRegistrarDocente.setSize(850, 529);
        pnlRegistrarDocente.setLocation(0, 0);
        add(pnlRegistrarDocente);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnRegistroDocenteActionPerformed

    private void btnIngresoCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoCalificacionesActionPerformed
        pContenedor.setVisible(false);
        pnlNotas.setVisible(true);
        pnlNotas.setSize(850, 529);
        pnlNotas.setLocation(0, 0);
        add(pnlNotas);
        revalidate();
        repaint();  
    }//GEN-LAST:event_btnIngresoCalificacionesActionPerformed

    public void limpiar(){
        pnlRegistrarDocente.setVisible(false);
        pnlNotas.setVisible(false);
        pContenedor.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresoCalificaciones;
    private javax.swing.JButton btnRegistroDocente;
    private javax.swing.JPanel pContenedor;
    // End of variables declaration//GEN-END:variables
}
