/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.paa.vista;

import com.paa.modelo.Categoria;
import com.paa.modelo.Curso;
import com.paa.modelo.Docente;
import com.paa.modelo.Nivel;
import com.paa.modelo.Validadores;
import javax.swing.JOptionPane;

/**
 *
 * @author Adhisson
 */
public class PnlRegistroCurso extends javax.swing.JPanel {
       
    
    /**
     * Creates new form PnlRegistroEstudiante
     */
    public PnlRegistroCurso() {
        initComponents();
        lblErrorDuracion.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreCurso = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblErrorDuracion = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescripcionCurso = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cmbNivel = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaRequisistosEspecificos = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        cmbDocentes = new javax.swing.JComboBox<>();

        jLabel1.setText("Nombre del curso:");

        jLabel2.setText("Categoría:");

        jLabel3.setText("Descripción del curso: ");

        jLabel4.setText("Duración (hrs)");

        txtNombreCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreCursoKeyReleased(evt);
            }
        });

        txtDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDuracionKeyReleased(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblErrorDuracion.setForeground(java.awt.Color.red);
        lblErrorDuracion.setText("Ingrese una duración válida");

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txaDescripcionCurso.setColumns(20);
        txaDescripcionCurso.setRows(5);
        jScrollPane1.setViewportView(txaDescripcionCurso);

        jLabel5.setText("Nivel: ");

        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNivel.setSelectedIndex(-1);

        jLabel6.setText("Requisitos específicos: ");

        txaRequisistosEspecificos.setColumns(20);
        txaRequisistosEspecificos.setRows(5);
        jScrollPane2.setViewportView(txaRequisistosEspecificos);

        jLabel7.setText("Docente: ");

        cmbDocentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDocentes.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(cmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreCurso)
                            .addComponent(txtDuracion)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblErrorDuracion))
                            .addComponent(cmbNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDocentes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnGuardar)))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(lblErrorDuracion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnGuardar)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            String nombreCurso = txtNombreCurso.getText();
        int duracion = Integer.parseInt(txtDuracion.getText());
        String  descripcion = txaDescripcionCurso.getText();
        
        Nivel nivelSelecionado = FrmMenuPrincipal.niveles.get(cmbNivel.getSelectedIndex());
        Categoria categoriaSeleccionada = FrmMenuPrincipal.categorias.get(cmbCategoria.getSelectedIndex());
        String requisitosEspecificos = txaRequisistosEspecificos.getText();
        // relacion de asociación
        categoriaSeleccionada.agregarCurso(new Curso(nombreCurso, descripcion, duracion, requisitosEspecificos, nivelSelecionado));
        
        Docente docenteSeleccionado = FrmMenuPrincipal.docentes.get(cmbDocentes.getSelectedIndex());
        int indiceUltimoElemento = categoriaSeleccionada.getCursos().size() - 1;
        docenteSeleccionado.agregarCurso(categoriaSeleccionada.getCursos().get(indiceUltimoElemento));
        
        JOptionPane.showMessageDialog(null, "El curso se registro con exito");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al registrar el curso");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCursoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCursoKeyReleased

    private void txtDuracionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuracionKeyReleased
        // TODO add your handling code here:
        if(Validadores.validadorDigitos(txtDuracion.getText())){
            lblErrorDuracion.setVisible(false);
            btnGuardar.setEnabled(true);
        } else {
            lblErrorDuracion.setVisible(true);
            btnGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_txtDuracionKeyReleased
    
    public void mostrarCategorias(){
        
        cmbCategoria.removeAllItems();
        
        // recorrer la lsta de categorias
        // extraer el nombre de cada categoria de la lista
        // colocar ese nombre en el combocategorias
        for ( int i = 0; i < FrmMenuPrincipal.categorias.size(); i++){
            cmbCategoria.addItem(FrmMenuPrincipal.categorias.get(i).getNombre());  
        }  
    }
    
    public void mostrarNiveles(){
        cmbNivel.removeAllItems();
        for(Nivel n: FrmMenuPrincipal.niveles){
            cmbNivel.addItem(n.getNombre());
        }
    }
    
    public void mostrarDocentes(){
        cmbNivel.removeAllItems();
        // se presentara el nombre y apellido del docente
        for(Docente d: FrmMenuPrincipal.docentes){
            cmbNivel.addItem(d.getNombre() +" "+ d.getApellido());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbDocentes;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblErrorDuracion;
    private javax.swing.JTextArea txaDescripcionCurso;
    private javax.swing.JTextArea txaRequisistosEspecificos;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombreCurso;
    // End of variables declaration//GEN-END:variables
}
