/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz.panelesPrincipales;

import CapaInterfaz.panelesSecundarios.PnlMatriculacionEstudiante;
import CapaInterfaz.panelesSecundarios.PnlRegistroEstudiante;
import CapaInterfaz.panelesSecundarios.PnlReporteEstudiante;

public class PnlEstudiante extends javax.swing.JPanel {

    PnlMatriculacionEstudiante pnlMatriculacionEstudiante;
    PnlRegistroEstudiante pnlRegistroeEstudiante;
    PnlReporteEstudiante pnlReporteEstudiante;
    
    public PnlEstudiante() {
        
        initComponents();
        pnlMatriculacionEstudiante = new PnlMatriculacionEstudiante();
        pnlRegistroeEstudiante = new PnlRegistroEstudiante();
        pnlReporteEstudiante = new PnlReporteEstudiante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContenedor = new javax.swing.JPanel();
        btnMatriculacionEtd = new javax.swing.JButton();
        btnRegistroEtd = new javax.swing.JButton();
        btnReportesEstudiante = new javax.swing.JButton();

        btnMatriculacionEtd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 36.png"))); // NOI18N
        btnMatriculacionEtd.setText("Matriculación ");
        btnMatriculacionEtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatriculacionEtdActionPerformed(evt);
            }
        });

        btnRegistroEtd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 5.png"))); // NOI18N
        btnRegistroEtd.setText("Registro del Estudiante");
        btnRegistroEtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEtdActionPerformed(evt);
            }
        });

        btnReportesEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaInterfaz/Imagenes/Recurso 3.png"))); // NOI18N
        btnReportesEstudiante.setText("Reportes Estudiante");
        btnReportesEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pContenedorLayout = new javax.swing.GroupLayout(pContenedor);
        pContenedor.setLayout(pContenedorLayout);
        pContenedorLayout.setHorizontalGroup(
            pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContenedorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnMatriculacionEtd, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(btnRegistroEtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(btnReportesEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        pContenedorLayout.setVerticalGroup(
            pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContenedorLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(pContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMatriculacionEtd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroEtd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportesEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesEstudianteActionPerformed
        limpiar();
        pContenedor.setVisible(false);
        pnlReporteEstudiante.setVisible(true);
        pnlReporteEstudiante.setSize(850, 529);
        pnlReporteEstudiante.setLocation(0, 0);
        add(pnlReporteEstudiante);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnReportesEstudianteActionPerformed

    private void btnMatriculacionEtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatriculacionEtdActionPerformed
        limpiar();
        pContenedor.setVisible(false);
        pnlMatriculacionEstudiante.setVisible(true);
        pnlMatriculacionEstudiante.setSize(850, 529);
        pnlMatriculacionEstudiante.setLocation(0, 0);
        add(pnlMatriculacionEstudiante);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnMatriculacionEtdActionPerformed

    private void btnRegistroEtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEtdActionPerformed
        limpiar();
        pContenedor.setVisible(false);
        pnlRegistroeEstudiante.setVisible(true);
        pnlRegistroeEstudiante.setSize(850, 529);
        pnlRegistroeEstudiante.setLocation(0, 0);
        add(pnlRegistroeEstudiante);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnRegistroEtdActionPerformed

    public void limpiar(){
        pnlMatriculacionEstudiante.setVisible(false);
        pnlReporteEstudiante.setVisible(false);
        pnlRegistroeEstudiante.setVisible(false);
        pContenedor.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMatriculacionEtd;
    private javax.swing.JButton btnRegistroEtd;
    private javax.swing.JButton btnReportesEstudiante;
    private javax.swing.JPanel pContenedor;
    // End of variables declaration//GEN-END:variables
}
